name: Test Auth Secret

on:
    push:
        branches: [main, master] # Pokreće se na push u main ili master granu

jobs:
    check-secret:
        runs-on: ubuntu-latest
        steps:
            - name: Provjera ključa
              env:
                  MOJ_KLJUC: ${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }}
              run: |
                  if [ -z "$MOJ_KLJUC" ]; then
                    echo "❌ Greška: Ključ NIJE pronađen u GitHub Secrets!"
                    exit 1
                  else
                    echo "✅ Uspjeh: Ključ je uspješno konfiguriran!"
                  fi
